name: Riepilogo Task Discord

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  aggiorna:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Installa dipendenze
        run: pip install requests pytz

      - name: Esegui script
        env:
          NOTION_TOKEN:          ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID:    ${{ secrets.NOTION_DATABASE_ID }}
          DISCORD_WEBHOOK_ID:    ${{ secrets.DISCORD_WEBHOOK_ID }}
          DISCORD_WEBHOOK_TOKEN: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          DISCORD_MESSAGE_ID:    ${{ secrets.DISCORD_MESSAGE_ID }}
        run: python riepilogo_task.py
